### ISSUE TITLE
OpenSSL error UNSUPPORTED_ALGORITHM when using mlspp with gRPC

### ISSUE THREAD

**Issue by ojroques** [cisco/mlspp#232]
Hello,

I'm building a small client app using mlspp and gRPC to communicate with a remote gRPC server. However my app crashes with the following error when trying to generate a new private key:
```bash
terminate called after throwing an instance of 'std::runtime_error'
  what():  error:06000080:public key routines:OPENSSL_internal:UNSUPPORTED_ALGORITHM
```

I've managed to reproduce the error with the following minimal example:

*testapp.cpp*:
```cpp
#include <grpcpp/create_channel.h>
#include <mls/crypto.h>

int main() {
  std::shared_ptr<grpc::ChannelInterface> chan = grpc::CreateChannel(
      "localhost:50051", grpc::InsecureChannelCredentials());

  auto sig_priv = mls::SignaturePrivateKey::generate(
      mls::CipherSuite::ID::X25519_AES128GCM_SHA256_Ed25519);
}
```

*CmakeLists.txt*:
```cmake
cmake_minimum_required(VERSION 3.15)

project(testapp
  VERSION 0.1
  LANGUAGES CXX
)

set(CMAKE_CXX_STANDARD 17)

find_package(MLSPP REQUIRED)
find_package(OpenSSL 1.1 REQUIRED)
find_package(Protobuf REQUIRED)
find_package(gRPC REQUIRED)

add_executable("testapp" "${CMAKE_CURRENT_SOURCE_DIR}/testapp.cpp")
target_link_libraries("testapp" MLSPP::mlspp gRPC::grpc++)
```

And the corresponding backtrace (mlspp is compiled on [master](https://github.com/cisco/mlspp/commit/90cc8cbf314e145bd3ace59f8f5f84a71626ef0f) in debug mode):
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff77a7859 in __GI_abort () at abort.c:79
#2  0x00007ffff7b7c911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7b8838c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7b883f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7b886a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555555c2d11 in hpke::RawKeyGroup::deserialize_private (this=0x555555ee9880 <hpke::Group::get<(hpke::Group::ID)5>()::instance>, skm=std::vector of length 32, capacity 32 = {...})
    at /home/olivier/Documents/mlspp/lib/hpke/src/group.cpp:378
#7  0x00005555555c2747 in hpke::RawKeyGroup::derive_key_pair (this=0x555555ee9880 <hpke::Group::get<(hpke::Group::ID)5>()::instance>, suite_id=std::vector of length 0, capacity 0,
    ikm=std::vector of length 32, capacity 32 = {...}) at /home/olivier/Documents/mlspp/lib/hpke/src/group.cpp:331
#8  0x00005555555bff9e in hpke::EVPGroup::generate_key_pair (this=0x555555ee9880 <hpke::Group::get<(hpke::Group::ID)5>()::instance>) at /home/olivier/Documents/mlspp/lib/hpke/src/group.cpp:47
#9  0x00005555555b8f60 in hpke::GroupSignature::generate_key_pair (this=0x555555ee93d0 <hpke::Signature::get<(hpke::Signature::ID)3>()::instance>) at /home/olivier/Documents/mlspp/lib/hpke/src/signature.cpp:55
#10 0x000055555559f7cf in mls::SignaturePrivateKey::generate (suite=...) at /home/olivier/Documents/mlspp/src/crypto.cpp:322
#11 0x000055555559d224 in main () at /home/olivier/.tmp/mlspp/testapp.cpp:9
```

What is strange is that the error disappears when I remove this line:
```cpp
std::shared_ptr<grpc::ChannelInterface> chan = grpc::CreateChannel(
      "localhost:50051", grpc::InsecureChannelCredentials());
```
it's only the combination of gRPC and MLSPP that makes the app crash. There must be some kind of internal conflicts somewhere but I've no clue where exactly.

**Comment by ojroques** [comment]
The issue comes from gRPC and OpenSSL, not MLS. I've opened an issue in gRPC [here](https://github.com/cisco/mlspp/issues/232).
